services:
  comfyui:
    image: joepitt91/comfyui:cpu
    # O para ARM64 CPU: ardenius/comfyui-cpu:latest
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - comfyui-models:/opt/ComfyUI/models
      - comfyui-output:/opt/ComfyUI/output
      - comfyui-input:/opt/ComfyUI/input
      - comfyui-custom-nodes:/opt/ComfyUI/custom_nodes
    environment:
      - CLI_ARGS=--cpu --listen 0.0.0.0 --port 8188

volumes:
  comfyui-models:
  comfyui-output:
  comfyui-input:
  comfyui-custom-nodes: